### ISSUE TITLE
【TODO】migrate to butterfly theme

### ISSUE THREAD

**Issue by SekiBetu** [SekiBetu/SekiBetu.github.io#2]
- [x] 抽空把博客主题从 [Matery](https://github.com/blinkfox/hexo-theme-matery) 迁移到 [Butterfly](https://github.com/jerryc127/hexo-theme-butterfly)
- [x] 弃用前景不明的yarn，用回npm
- [x] ~~去二次元化，将文章封面图改为相关内容~~ 去除文章封面图
- [x] ~~重新整理流水账笔记，能让人看懂~~ 看得懂看，看不懂拉倒

**Comment by SekiBetu** [comment]
1
